development: 
  domain: mail.rhomobile.com
  sender: admin@rhomobile.com
  name: Admin
  bbserver: 192.168.10.77
  iphoneserver: gateway.sandbox.push.apple.com
  iphoneport: 2195
  iphonepassphrase: something
  iphonecert: config/apple_push_cert.pem
  sync_popup: New synchronized data
  sync_vibrate: 1000
    
test:
  domain: mail.rhomobile.com
  sender: admin@rhomobile.com
  name: Admin
  bbserver: 192.168.10.77
  iphoneserver: gateway.sandbox.push.apple.com
  iphoneport: 2195
  iphonepassphrase: something
  iphonecert: config/apple_push_cert.pem
  sync_popup: New synchronized data
  sync_vibrate: 1000
  
production:
  domain: mail.rhomobile.com
  sender: admin@rhomobile.com
  name: Admin
  bbserver: 192.168.10.77
  iphoneserver: gateway.push.apple.com
  iphoneport: 2195  
  iphonepassphrase: something
  iphonecert: config/apple_push_cert.pem
  sync_popup: New synchronized data
  sync_vibrate: 1000