AeropriseCategory:
  id: 1
  name: AeropriseCategory
  adapter: AeropriseCategory
  app_id: 1
  limit: 1000000
  pollinterval: 300000

AeropriseRequest:
  id: 2
  name: AeropriseRequest
  adapter: AeropriseRequest
  app_id: 1
  limit: 1000000
  pollinterval: 300000

AeropriseRequestAction:
  id: 3
  name: AeropriseRequestAction
  adapter: AeropriseRequestAction
  app_id: 1
  limit: 1000000
  pollinterval: 300000

AeropriseSrd:
  id: 4
  name: AeropriseSrd
  adapter: AeropriseSrd
  app_id: 1
  limit: 1000000
  pollinterval: 300000

AeropriseUser:
  id: 5
  name: AeropriseUser
  adapter: AeropriseUser
  app_id: 1
  limit: 1000000
  pollinterval: 300000

AeropriseWorklog:
  id: 6
  name: AeropriseWorklog
  adapter: AeropriseWorklog
  app_id: 1
  limit: 1000000
  pollinterval: 300000

