SugarAccounts:
  id: 1
  name: SugarAccounts
  adapter: SugarAccounts
  app_id: 1

SugarCases:
  id: 2
  name: SugarCases
  app_id: 1
  adapter: SugarCases

SugarEmployees:
  id: 3
  name: SugarEmployees
  app_id: 1
  adapter: SugarEmployees
  
SugarContacts:
  id: 11
  name: SugarContacts
  app_id: 1
  adapter: SugarContacts
  
SugarLeads:
  id: 12
  name: SugarLeads
  app_id: 1
  adapter: SugarLeads
  
SugarOpportunities:
  id: 13
  name: SugarOpportunities
  app_id: 1
  adapter: SugarOpportunities
    
SugarMeetings:
  id: 14
  name: SugarMeetings
  app_id: 1
  adapter: SugarMeetings
    
SugarCalls:
  id: 15
  name: SugarCalls
  app_id: 1
  adapter: SugarCalls

SugarCampaigns:
  id: 16
  name: SugarCampaigns
  app_id: 1
  adapter: SugarCampaigns
    
SugarProducts:
  id: 17
  name: SugarProducts
  app_id: 1
  adapter: SugarProducts
      
SugarTeams:
  id: 18
  name: SugarTeams
  app_id: 1
  adapter: SugarTeams
  
SugarUsers:
  id: 19
  name: SugarUsers
  app_id: 1
  adapter: SugarUsers
  
SugarQuotes:
  id: 21
  name: SugarQuotes
  app_id: 1
  adapter: SugarQuotes
    
SiebelServiceRequests:
  id: 4
  name: SiebelServiceRequests
  url: secure-ausomxbha.crmondemand.com
  login: RHOMOBILE/ADAM@RHOMOBILE.COM
  password: password1
  app_id: 2

LighthouseProjects:
  id: 5
  app_id: 4
  adapter: "LighthouseProjects"
  name: "LighthouseProjects"
  url: "http://rhomobile.lighthouseapp.com"
  login: 
  password: 

  
LighthouseMilestones:
  id: 6
  app_id: 4
  adapter: "LighthouseMilestones"
  name: "LighthouseMilestones"
  url: "http://rhomobile.lighthouseapp.com"
  login: 
  password: 
  
LighthouseTickets:
  id: 7
  app_id: 4
  adapter: "LighthouseTickets"
  name: "LighthouseTickets"
  url: "http://rhomobile.lighthouseapp.com"
  login: 
  password: 

LighthouseUsers:
  id: 8
  app_id: 4
  adapter: "LighthouseUsers"
  name: "LighthouseUsers"
  url: "http://rhomobile.lighthouseapp.com"
  login: 
  password: 
  
LighthouseTicketVersions:
  id: 9
  app_id: 4
  adapter: "LighthouseTicketVersions"
  name: "LighthouseTicketVersions"
  url: "http://rhomobile.lighthouseapp.com"
  login: 
  password: 
  
LighthouseSettings:
  id: 10
  app_id: 4
  adapter: "LighthouseSettings"
  name: "LighthouseSettings"
  url: "http://rhomobile.lighthouseapp.com"
  login: 
  password: 
      
